# Generated by Django 6.0 on 2026-01-06 14:04

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Allergen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название аллергена')),
                ('code', models.CharField(blank=True, help_text='Например: A, B, C или цифровой код', max_length=10, verbose_name='Код аллергена')),
                ('description', models.TextField(blank=True, help_text='Какие продукты содержат, симптомы реакции', verbose_name='Описание аллергена')),
            ],
            options={
                'verbose_name': 'Аллерген',
                'verbose_name_plural': 'Аллергены',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название категории')),
                ('description', models.TextField(blank=True, verbose_name='Описание категории')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Официальное или общепринятое название продукта', max_length=100, unique=True, verbose_name='Уникальное название')),
                ('display_name', models.CharField(blank=True, help_text='Короткое название для интерфейса (автозаполнение)', max_length=50, verbose_name='Название для отображения')),
                ('description', models.TextField(blank=True, help_text='Подробное описание, история, особенности использования', verbose_name='Описание')),
                ('calories', models.PositiveSmallIntegerField(blank=True, help_text='ккал на 100 г продукта', null=True, validators=[django.core.validators.MaxValueValidator(1000), django.core.validators.MinValueValidator(0)], verbose_name='Калории')),
                ('protein', models.DecimalField(blank=True, decimal_places=1, help_text='г на 100 г продукта', max_digits=4, null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='Белки')),
                ('fat', models.DecimalField(blank=True, decimal_places=1, help_text='г на 100 г продукта', max_digits=4, null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='Жиры')),
                ('carbohydrates', models.DecimalField(blank=True, decimal_places=1, help_text='г на 100 г продукта', max_digits=4, null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='Углеводы')),
                ('fiber', models.DecimalField(blank=True, decimal_places=1, help_text='г на 100 г продукта', max_digits=4, null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='Пищевые волокна')),
                ('allergen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.allergen', verbose_name='Основной аллерген')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Ингредиент',
                'verbose_name_plural': 'Ингредиенты',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Pairing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pairing_type', models.CharField(choices=[('cook', 'Для готовки'), ('serve', 'Для подачи')], default='cook', max_length=10, verbose_name='Тип сочетания')),
                ('ingredient_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pairings_as_a', to='backend.ingredient', verbose_name='Первый ингредиент')),
                ('ingredient_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pairings_as_b', to='backend.ingredient', verbose_name='Второй ингредиент')),
            ],
            options={
                'verbose_name': 'Сочетание',
                'verbose_name_plural': 'Сочетания',
            },
        ),
        migrations.AddIndex(
            model_name='ingredient',
            index=models.Index(fields=['title'], name='backend_ing_title_0c438c_idx'),
        ),
        migrations.AddIndex(
            model_name='ingredient',
            index=models.Index(fields=['category'], name='backend_ing_categor_9a1562_idx'),
        ),
        migrations.AddIndex(
            model_name='ingredient',
            index=models.Index(fields=['calories'], name='backend_ing_calorie_d4be84_idx'),
        ),
        migrations.AddIndex(
            model_name='ingredient',
            index=models.Index(fields=['allergen'], name='backend_ing_allerge_8a0c41_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='pairing',
            unique_together={('ingredient_a', 'ingredient_b', 'pairing_type')},
        ),
    ]
