# Generated by Django 6.0 on 2026-01-11 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='pairing',
            index=models.Index(fields=['ingredient_a', 'pairing_type'], name='backend_pai_ingredi_71daf6_idx'),
        ),
        migrations.AddIndex(
            model_name='pairing',
            index=models.Index(fields=['ingredient_b', 'pairing_type'], name='backend_pai_ingredi_375321_idx'),
        ),
    ]
